### ISSUE TITLE
Create a docs website

### ISSUE THREAD

**Issue by andreterron** [andreterron/mainframe#8]
It will make us look more like a dev tool instead of a no-code website.

### Docs frameworks

* [Docusaurus](https://docusaurus.io/)
* [MkDocs](https://www.mkdocs.org/)
* [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)
* [Mintlify](https://mintlify.com/)
* [Vitepress](https://vitepress.dev/): Vue. Found it [here](https://github.com/kubb-labs/kubb/tree/main/docs).
* Astro Starlight: Astro

### To-Do

- [X] Define which docs framework to use
- [X] Create a `/package/docs` package with a template from one of the frameworks above
- [X] Add a page for "Getting Started"
- [X] Create placeholder pages (no content) for other relevant sections (e.g.: How to add a new integration, Security, Building an App, ...)
- [X] Host the page somewhere
- [X] Cancel super.so subscription
